using System;
using System.Collections.Generic;

#nullable disable

namespace TexberAPI.Models
{
    public partial class Articulo
    {
        public short CodigoEmpresa { get; set; } = 1;
        public string CodigoArticulo { get; set; }
        public string DescripcionArticulo { get; set; }
        public string Descripcion2Articulo { get; set; }
        public string DescripcionLinea { get; set; }
        public string ComentarioArticulo { get; set; }
        public string MarcaProducto { get; set; }
        public string CodigoAlternativo { get; set; }
        public string CodigoAlternativo2 { get; set; }
        public string CodigoArticuloOferta { get; set; }
        public string CodigoArancelario { get; set; }
        public string CodigoProveedor { get; set; }
        public string ReferenciaEdi { get; set; }
        public short PublicarInternet { get; set; }
        public string TipoArticulo { get; set; }
        public short Utilizado { get; set; }
        public DateTime? FechaAlta { get; set; }
        public DateTime? FechaInicioOferta { get; set; }
        public DateTime? FechaFinalOferta { get; set; }
        public string Temporada { get; set; }
        public int TipoEnvase { get; set; }
        public string UnidadMedida2 { get; set; }
        public string UnidadMedidaAlternativa { get; set; }
        public decimal FactorConversion { get; set; }
        public string CodigoFamilia { get; set; }
        public string CodigoSubfamilia { get; set; }
        public string CodigoDivisa { get; set; }
        public string CodigoProyecto { get; set; }
        public string CodigoSeccion { get; set; }
        public string CodigoDepartamento { get; set; }
        public string CodigoDefinicion { get; set; }
        public byte ValoracionStock { get; set; }
        public short TratamientoPartidas { get; set; }
        public int ContadorPartida { get; set; }
        public short Colores { get; set; }
        public short GrupoTalla { get; set; }
        public short AcumulaEstadistica { get; set; }
        public short GeneraCompraAutomatica { get; set; }
        public short IvaIncluido { get; set; }
        public short BloqueoCompra { get; set; }
        public short BloqueoPedidoCompra { get; set; }
        public short BloqueoAlbaranVenta { get; set; }
        public short BloqueoPedidoVenta { get; set; }
        public decimal UnidadesMinimasOferta { get; set; }
        public decimal UnidadesRegaloOferta { get; set; }
        public decimal StockMinimo { get; set; }
        public decimal StockMaximo { get; set; }
        public decimal PuntoPedido { get; set; }
        public int LotePedido { get; set; }
        public byte GrupoIva { get; set; }
        public byte GrupoIvaCompras { get; set; }
        public decimal PrecioCompra { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal Margen { get; set; }
        public decimal CosteFabricacionUnitario { get; set; }
        public decimal PrecioCosteEstandar { get; set; }
        public decimal PrecioVentaconIva1 { get; set; }
        public decimal PrecioVentaconIva2 { get; set; }
        public decimal PrecioVentaconIva3 { get; set; }
        public decimal PrecioVentasinIva1 { get; set; }
        public decimal PrecioVentasinIva2 { get; set; }
        public decimal PrecioVentasinIva3 { get; set; }
        public decimal PrecioOfertaconIva { get; set; }
        public decimal PrecioOfertasinIva { get; set; }
        public decimal Descuento { get; set; }
        public decimal Descuento2 { get; set; }
        public decimal Descuento3 { get; set; }
        public decimal DescuentoCompras { get; set; }
        public decimal DescuentoCompras2 { get; set; }
        public decimal DescuentoCompras3 { get; set; }
        public decimal DescuentoOferta { get; set; }
        public short AplicarDescuentos { get; set; }
        public int CodigoComisionista { get; set; }
        public int CodigoComisionista2 { get; set; }
        public int CodigoComisionista3 { get; set; }
        public int CodigoComisionista4 { get; set; }
        public decimal Comision { get; set; }
        public decimal Comision2 { get; set; }
        public decimal Comision3 { get; set; }
        public decimal Comision4 { get; set; }
        public decimal PesoBrutoUnitario { get; set; }
        public decimal PesoNetoUnitario { get; set; }
        public decimal VolumenUnitario { get; set; }
        public short FormulaLote { get; set; }
        public short Lote { get; set; }
        public short Formula { get; set; }
        public int LoteFabricacion { get; set; }
        public short NivelCompuesto { get; set; }
        public string TipoDemanda { get; set; }
        public short GenerarPlanProd { get; set; }
        public short UsarStockSeg { get; set; }
        public short StockSeguridad { get; set; }
        public decimal DemandaMediaDiaria { get; set; }
        public decimal FactorCrecimiento { get; set; }
        public short PeriodosPromediar { get; set; }
        public decimal TasaProduccionDiaria { get; set; }
        public decimal TiempoMedioReposicion { get; set; }
        public short NumDecimalesUnidades { get; set; }
        public short PeriodoVida { get; set; }
        public string TipoAbc { get; set; }
        public string CodigoCategoriaLc { get; set; }
        public string CodigoSubcategoriaLc { get; set; }
        public string CodigoClaseArticuloLc { get; set; }
        public string CodigoTipoArticuloLc { get; set; }
        public string CodigoSubtipoArticuloLc { get; set; }
        public string CodigoGrupoArticuloLc { get; set; }
        public string CodigoSubgrupoArticuloLc { get; set; }
        public string CodigoModoLc { get; set; }
        public string CodigoFabricanteLc { get; set; }
        public string CodigoFamiliaFabricanteLc { get; set; }
        public string CodigoConjuntoLc { get; set; }
        public string CodigoSubconjuntoLc { get; set; }
        public decimal MaximoSinRetencionLc { get; set; }
        public short TrataNumerosSerieLc { get; set; }
        public short SonHorasLc { get; set; }
        public short ArticuloNoCodificadoLc { get; set; }
        public short PrecioCosteEditableLc { get; set; }
        public string CodigoTipoPeriodicidadPrecioLc { get; set; }
        public short LiquidableLc { get; set; }
        public string CodigoTipoCoberturaLc { get; set; }
        public short ObsoletoLc { get; set; }
        public string CodigoAreaCompetenciaLc { get; set; }
        public Guid ImagenExt { get; set; }
        public short GestionCompras { get; set; }
        public string UnidadMedidaCompras { get; set; }
        public string UnidadMedidaVentas { get; set; }
        public string UnidadMedidaFabricacion { get; set; }
        public string CodigoSerie { get; set; }
        public string UnidadMedidaSerie { get; set; }
        public int FactorPrecioCompra { get; set; }
        public int FactorPrecioVenta { get; set; }
        public byte TipoUnidadCalculo { get; set; }
        public string Medida { get; set; }
        public string TipoArticuloPresupuesto { get; set; }
        public short TipoCodificado { get; set; }
        public string CodigoPeriodicidadPrecio { get; set; }
        public short CobrarDevolucionTardia { get; set; }
        public short CobrarEntregaAdelantada { get; set; }
        public short DevolverDevolucionAdelantada { get; set; }
        public short DevolverEntregaTardia { get; set; }
        public string CodigoArticuloFacturacion { get; set; }
        public decimal PrecioPeriodoRetraso { get; set; }
        public decimal PrecioUnidadPerdida { get; set; }
        public short PartirPeriodos { get; set; }
        public short TipoArticuloAlquiler { get; set; }
        public short NoTraspasarSfa { get; set; }
        public string CodigoContaje { get; set; }
        public short PrecioPorTramos { get; set; }
        public short Suplido { get; set; }
        public short CodigoNacionOrigen { get; set; }
        public short TipoCodigoBarrasSr { get; set; }
        public short PesableSr { get; set; }
        public string ImagenTactilSr { get; set; }
        public decimal TaraUnitaria { get; set; }
        public short PrecioModificableSr { get; set; }
        public short NoAgruparSr { get; set; }
        public short EnviaraSr { get; set; }
        public short ImpresionResguardoSr { get; set; }
        public short PeriodoGarantiaSr { get; set; }
        public short NovedadesWeb { get; set; }
        public Guid IdArticulo { get; set; }
        public short PublicarGcrm { get; set; }
        public short MesesGarantiaVenta { get; set; }
        public short MesesGarantiaCompra { get; set; }
        public short MesesGarantiaReparacion { get; set; }
    }
}
