using System;
using System.Collections.Generic;

#nullable disable

namespace TexberAPI.Models
{
    public partial class Cliente
    {
        public short CodigoEmpresa { get; set; } = 1;
        public string IdDelegacion { get; set; }
        public string CodigoCliente { get; set; }
        public string SiglaNacion { get; set; }
        public string CifDni { get; set; }
        public string CifEuropeo { get; set; }
        public DateTime FechaAlta { get; set; }
        public string CodigoProveedor { get; set; }
        public string CodigoContable { get; set; }
        public string CodigoCadena { get; set; }
        public string CodigoCategoriaCliente { get; set; }
        public string CodigoDefinicion { get; set; }
        public string ReferenciaEdi { get; set; }
        public short ActivarLogicNet { get; set; }
        public string UsuarioLogicNet { get; set; }
        public string ContraseñaLogicNet { get; set; }
        public string CodigoExportacion { get; set; }
        public string CondicionExportacion { get; set; }
        public string CodigoDivisa { get; set; }
        public short CodigoCondiciones { get; set; }
        public string CodigoIdioma { get; set; }
        public string RazonSocial { get; set; }
        public string RazonSocial2 { get; set; }
        public string Nombre { get; set; }
        public string Domicilio { get; set; }
        public string Domicilio2 { get; set; }
        public string Actividad { get; set; }
        public string TipoCliente { get; set; }
        public string CodigoSector { get; set; }
        public string Marca { get; set; }
        public string Cargo1 { get; set; }
        public string Nombre1 { get; set; }
        public string Cargo2 { get; set; }
        public string Nombre2 { get; set; }
        public string Cargo3 { get; set; }
        public string Nombre3 { get; set; }
        public string FormadePago { get; set; }
        public short DomicilioEnvio { get; set; }
        public short DomicilioFactura { get; set; }
        public short DomicilioRecibo { get; set; }
        public string CodigoBanco { get; set; }
        public string CodigoAgencia { get; set; }
        public string Dc { get; set; }
        public string Ccc { get; set; }
        public string Iban { get; set; }
        public short BloqueoPedido { get; set; }
        public short BloqueoAlbaran { get; set; }
        public string CodigoCanal { get; set; }
        public string CodigoProyecto { get; set; }
        public string CodigoSeccion { get; set; }
        public string CodigoDepartamento { get; set; }
        public short TarifaPrecio { get; set; }
        public short TarifaDescuento { get; set; }
        public short MantenerCambio { get; set; }
        public string IndicadorIva { get; set; }
        public byte GrupoIva { get; set; }
        public decimal Descuento { get; set; }
        public decimal ProntoPago { get; set; }
        public decimal Retencion { get; set; }
        public decimal Financiacion { get; set; }
        public decimal Rappel { get; set; }
        public int CodigoComisionista { get; set; }
        public int CodigoComisionista2 { get; set; }
        public int CodigoComisionista3 { get; set; }
        public int CodigoComisionista4 { get; set; }
        public int CodigoJefeZona { get; set; }
        public decimal Comision { get; set; }
        public decimal Comision2 { get; set; }
        public decimal Comision3 { get; set; }
        public decimal Comision4 { get; set; }
        public decimal ComisionSobreZona { get; set; }
        public int CodigoZona { get; set; }
        public string CodigoRuta { get; set; }
        public int CodigoTransportista { get; set; }
        public string TipoPortes { get; set; }
        public string ObservacionesCliente { get; set; }
        public string Comentarios { get; set; }
        public byte PeriodicidadFacturas { get; set; }
        public short AgruparAlbaranes { get; set; }
        public short AgruparAbonos { get; set; }
        public short AlbaranValorado { get; set; }
        public short ServirCompleto { get; set; }
        public string MascaraOferta { get; set; }
        public string MascaraPedido { get; set; }
        public string MascaraAlbaran { get; set; }
        public string MascaraFactura { get; set; }
        public string MascaraRecibo { get; set; }
        public string SerieOferta { get; set; }
        public string SeriePedido { get; set; }
        public string SerieAlbaran { get; set; }
        public byte CopiasAlbaran { get; set; }
        public byte CopiasFactura { get; set; }
        public byte CopiasOferta { get; set; }
        public byte CopiasPedido { get; set; }
        public string CodigoSigla { get; set; }
        public string ViaPublica { get; set; }
        public string Numero1 { get; set; }
        public string Numero2 { get; set; }
        public string Escalera { get; set; }
        public string Piso { get; set; }
        public string Puerta { get; set; }
        public string Letra { get; set; }
        public string CodigoPostal { get; set; }
        public string CodigoMunicipio { get; set; }
        public string Municipio { get; set; }
        public string ColaMunicipio { get; set; }
        public string CodigoProvincia { get; set; }
        public string Provincia { get; set; }
        public short CodigoNacion { get; set; }
        public string Nacion { get; set; }
        public string Telefono { get; set; }
        public string Telefono2 { get; set; }
        public string Telefono3 { get; set; }
        public string Fax { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public short BajaEmpresaLc { get; set; }
        public DateTime? FechaBajaLc { get; set; }
        public string CodigoMotivoBajaClienteLc { get; set; }
        public int ComercialAsignadoLc { get; set; }
        public string CodigoTipoClienteLc { get; set; }
        public DateTime? FechaUltimaAccionLc { get; set; }
        public string PersonaClienteLc { get; set; }
        public string CodigoActividadLc { get; set; }
        public string CodigoSubActividadLc { get; set; }
        public string CodigoCargo1 { get; set; }
        public string CodigoCargo2 { get; set; }
        public string CodigoCargo3 { get; set; }
        public string CodigoDivisionLc { get; set; }
        public string CodigoAmbitoClienteLc { get; set; }
        public string CodigoClaseClienteLc { get; set; }
        public string CodigoGrupoClienteLc { get; set; }
        public string IdDelegacionCentralLc { get; set; }
        public string HorarioDomicilioLc { get; set; }
        public string CodigoColectivoClienteLc { get; set; }
        public string CodigoTipoPrimerContactoLc { get; set; }
        public DateTime? FechaProximaAccionLc { get; set; }
        public short AutorizacionLopdlc { get; set; }
        public DateTime? FechaAutorizacionLopdlc { get; set; }
        public short ExcluirPorLopdlc { get; set; }
        public DateTime? FechaExcluirPorLopdlc { get; set; }
        public decimal RiesgoMaximo { get; set; }
        public string ReferenciadelProveedor { get; set; }
        public short DestinoEdi { get; set; }
        public string CodigoNaturaleza { get; set; }
        public string CodigoTransporte { get; set; }
        public string CodigoPuerto { get; set; }
        public string CodigoRegimenEstadistico { get; set; }
        public short EnvioEfactura { get; set; }
        public string EmailEnvioEfactura { get; set; }
        public string GuiaXmlefactura { get; set; }
        public string DepartamentoEdi { get; set; }
        public short SabadosFestivos { get; set; }
        public short DomingosFestivos { get; set; }
        public byte FormatoEfactura { get; set; }
        public short NoTraspasarSfa { get; set; }
        public string CuentaProvision { get; set; }
        public short LiquidacionEnDespacho { get; set; }
        public string CodigoContableAnt { get; set; }
        public string CuentaProvisionAnt { get; set; }
        public string FormatoEnvio { get; set; }
        public decimal PuntosSr { get; set; }
        public string TarjetaSr { get; set; }
        public DateTime? FechaNacimiento { get; set; }
        public string PersonaAsignada { get; set; }
        public string AsesorNominaLw { get; set; }
        public string EmpresaNominaLwin { get; set; }
        public int CodigoEmpleado { get; set; }
        public Guid IdCliente { get; set; }
        public short PublicarGcrm { get; set; }
        public string ReferenciaMandato { get; set; }
        public string Social1 { get; set; }
        public string Social2 { get; set; }
        public string Social3 { get; set; }
        public string Social4 { get; set; }
        public string TelefonoAccion { get; set; }
        public string Telefono2Accion { get; set; }
        public string Telefono3Accion { get; set; }
        public string Social1Accion { get; set; }
        public string Social2Accion { get; set; }
        public string Social3Accion { get; set; }
        public string Social4Accion { get; set; }
        public string CuentaGasto { get; set; }
        public string ComentarioAsiento { get; set; }
        public string Dire { get; set; }
        public Guid IdClientePago { get; set; }
        public short StatusWf { get; set; }
        public short NoIdentificado { get; set; }
    }
}
