using System;
using System.Collections.Generic;

#nullable disable

namespace TexberAPI.Models
{
    public partial class LineasAlbaranCliente
    {
        public short CodigoEmpresa { get; set; } = 1;
        public short EjercicioAlbaran { get; set; } = (short)DateTime.Now.Year;
        public string SerieAlbaran { get; set; }
        public int NumeroAlbaran { get; set; }
        public short Orden { get; set; }
        public Guid LineasPosicion { get; set; }
        public Guid LineasPosicionCompuesto { get; set; }
        public Guid LineasPosicionRegalo { get; set; }
        public Guid LineaPedido { get; set; }
        public DateTime FechaRegistro { get; set; } = DateTime.Now;
        public DateTime FechaAlbaran { get; set; } = DateTime.Now;
        public string CodigoArticulo { get; set; }
        public string CodigoAlmacen { get; set; }
        public string AlmacenContrapartida { get; set; }
        public string Partida { get; set; }
        public string DescripcionArticulo { get; set; }
        public string Descripcion2Articulo { get; set; }
        public string DescripcionLinea { get; set; }
        public string CodigodelCliente { get; set; }
        public string CodigoFamilia { get; set; }
        public string CodigoSubfamilia { get; set; }
        public string UnidadMedida1 { get; set; }
        public string UnidadMedida2 { get; set; }
        public decimal FactorConversion { get; set; }
        public string CodigoProyecto { get; set; }
        public string CodigoSeccion { get; set; }
        public string CodigoDepartamento { get; set; }
        public short StatusStock { get; set; }
        public short StatusEstadis { get; set; }
        public short IvaIncluido { get; set; }
        public short BloqueoRebaje { get; set; }
        public short AcumulaEstadistica { get; set; }
        public string CodigoArancelario { get; set; }
        public string CodigoDefinicion { get; set; }
        public byte CodigoTransaccion { get; set; }
        public DateTime? FechaCaduca { get; set; }
        public string Ubicacion { get; set; }
        public string SuPedido { get; set; }
        public short EjercicioPedido { get; set; }
        public string SeriePedido { get; set; }
        public int NumeroPedido { get; set; }
        public short EjercicioFactura { get; set; }
        public string SerieFactura { get; set; }
        public int NumeroFactura { get; set; }
        public int CodigoComisionista { get; set; }
        public int CodigoComisionista2 { get; set; }
        public int CodigoComisionista3 { get; set; }
        public int CodigoComisionista4 { get; set; }
        public int CodigoJefeVenta { get; set; }
        public int CodigoJefeZona { get; set; }
        public string CodigoColor { get; set; }
        public short GrupoTalla { get; set; }
        public string CodigoTalla01 { get; set; }
        public byte GrupoIva { get; set; }
        public short CodigoIva { get; set; }
        public short FormulaLote { get; set; }
        public short Lote { get; set; }
        public short Componente { get; set; }
        public int TipoEnvase { get; set; }
        public decimal NumeroEnvases { get; set; }
        public int CodigoAgrupacion { get; set; }
        public int NumeroAgrupaciones { get; set; }
        public decimal UnidadesAgrupacion { get; set; }
        public decimal UnidadesServidas { get; set; }
        public decimal UnidadesRegalo { get; set; }
        public decimal Unidades { get; set; }
        public decimal Unidades2 { get; set; }
        public decimal Precio { get; set; }
        public decimal PrecioEnvase { get; set; }
        public decimal PrecioRebaje { get; set; }
        public decimal PrecioCoste { get; set; }
        public int Bultos { get; set; }
        public int OrdenBulto { get; set; }
        public decimal Descuento { get; set; }
        public decimal Descuento2 { get; set; }
        public decimal Descuento3 { get; set; }
        public decimal Iva { get; set; }
        public decimal Recargo { get; set; }
        public decimal BaseCorreccion { get; set; }
        public decimal Comision { get; set; }
        public decimal Comision2 { get; set; }
        public decimal Comision3 { get; set; }
        public decimal Comision4 { get; set; }
        public decimal ComisionSobreVenta { get; set; }
        public decimal ComisionSobreZona { get; set; }
        public decimal PesoBrutoUnitario { get; set; }
        public decimal PesoBruto { get; set; }
        public decimal PesoNetoUnitario { get; set; }
        public decimal PesoNeto { get; set; }
        public decimal VolumenUnitario { get; set; }
        public decimal Volumen { get; set; }
        public decimal ImporteCoste { get; set; }
        public decimal ImporteBruto { get; set; }
        public decimal ImporteBrutoDivisa { get; set; }
        public decimal ImporteDescuento { get; set; }
        public decimal ImporteDescuentoDivisa { get; set; }
        public decimal ImporteNeto { get; set; }
        public decimal ImporteNetoDivisa { get; set; }
        public decimal ImporteDescuentoCliente { get; set; }
        public decimal ImporteDtoClienteDivisa { get; set; }
        public decimal BaseComision { get; set; }
        public decimal BaseComisionDivisa { get; set; }
        public decimal ImporteComision { get; set; }
        public decimal ImporteComision2 { get; set; }
        public decimal ImporteComision3 { get; set; }
        public decimal ImporteComision4 { get; set; }
        public decimal ImporteComisionJefeVentas { get; set; }
        public decimal ImporteComisionJefeZona { get; set; }
        public decimal ImporteProntoPago { get; set; }
        public decimal ImporteProntoPagoDivisa { get; set; }
        public decimal BaseImponible { get; set; }
        public decimal BaseImponibleDivisa { get; set; }
        public decimal BaseIva { get; set; }
        public decimal BaseIvaDivisa { get; set; }
        public decimal CuotaIva { get; set; }
        public decimal CuotaIvaDivisa { get; set; }
        public decimal CuotaRecargo { get; set; }
        public decimal CuotaRecargoDivisa { get; set; }
        public decimal TotalIva { get; set; }
        public decimal TotalIvaDivisa { get; set; }
        public decimal ImporteLiquido { get; set; }
        public decimal ImporteLiquidoDivisa { get; set; }
        public decimal ImporteRappel { get; set; }
        public decimal ImporteRappelDivisa { get; set; }
        public decimal ImporteEnvases { get; set; }
        public decimal ImporteEnvasesDivisa { get; set; }
        public string CodigoCategoriaLc { get; set; }
        public string CodigoSubcategoriaLc { get; set; }
        public string CodigoTipoArticuloLc { get; set; }
        public string CodigoSubtipoArticuloLc { get; set; }
        public string CodigoGrupoArticuloLc { get; set; }
        public string CodigoSubgrupoArticuloLc { get; set; }
        public string CodigoModoLc { get; set; }
        public string CodigoFabricanteLc { get; set; }
        public string CodigoTipoPeriodicidadPrecioLc { get; set; }
        public string IdPrecioLc { get; set; }
        public string CodigoTipoOperacionLc { get; set; }
        public string CodigoFamiliaFabricanteLc { get; set; }
        public string CodigoConjuntoLc { get; set; }
        public string CodigoSubconjuntoLc { get; set; }
        public short TrataNumerosSerieLc { get; set; }
        public string CodigoAreaLc { get; set; }
        public string TipoArticulo { get; set; }
        public short ReservarStock { get; set; }
        public short AbonadaLc { get; set; }
        public decimal UnidadesAbonadasLc { get; set; }
        public Guid LineaPosAbonoLc { get; set; }
        public string NumeroSerieLc { get; set; }
        public int FactorPrecioVenta { get; set; }
        public byte TipoUnidadCalculo { get; set; }
        public decimal Largo { get; set; }
        public decimal Alto { get; set; }
        public decimal Ancho { get; set; }
        public decimal Dimension { get; set; }
        public string CodigoDun14 { get; set; }
        public decimal PorMargenBeneficio { get; set; }
        public decimal MargenBeneficio { get; set; }
        public decimal Unidades2AbonadasLc { get; set; }
        public string EdiSellerNumber { get; set; }
        public string EdiBatchNumber { get; set; }
        public string EdiIsbn { get; set; }
        public string EdiSerialNumber { get; set; }
        public string EdiEtiquetaEan { get; set; }
        public short EjercicioExpediente { get; set; }
        public string SerieExpediente { get; set; }
        public int NumeroExpediente { get; set; }
        public short Suplido { get; set; }
        public Guid MovOrigenSuplido { get; set; }
        public string CodigoPerceptor { get; set; }
        public string AnaLote { get; set; }
        public string AnaCapitulo { get; set; }
        public short PrecioTotal { get; set; }
        public short TarifaPrecioLin { get; set; }
        public short CoBobinas { get; set; }
        public Guid CoMovOrigen { get; set; }
        public string SuContrato { get; set; }
        public string CausaExencion { get; set; }
    }
}
